# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='artworkpage',
            old_name='feed_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='artworkattributionlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='artworkattributionlink',
            name='link_external',
        ),
        migrations.RemoveField(
            model_name='artworkattributionlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='artworkattributionlink',
            name='title',
        ),
        migrations.AddField(
            model_name='artworkattributionlink',
            name='artwork',
            field=modelcluster.fields.ParentalKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='artworkartistlink', to='artworks.ArtworkPage'),
            preserve_default=False,
        ),
    ]
