# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('artworks', '0002_auto_20160609_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkpage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
