# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSocialMediaContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('link_external', models.URLField(blank=True, verbose_name=b'External link')),
                ('handle', models.CharField(max_length=4000, verbose_name='Handle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
