# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0028_merge'),
        ('links', '0003_auto_20160622_1455'),
        ('home', '0002_auto_20160605_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSocialMediaContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('link_external', models.URLField(blank=True, verbose_name=b'External link')),
                ('handle', models.CharField(max_length=4000, verbose_name='Handle')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.RelatedLinkType', verbose_name='Link type')),
                ('site', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitesocialmediacontact', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('home.standardpage',),
        ),
    ]
