# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160704_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='body_classes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
