# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('wagtailcore', '0028_merge'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('bio', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('profile_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArtistSocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name=b'External link')),
                ('handle', models.CharField(max_length=4000, verbose_name='Handle')),
                ('artist', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedialink', to='artists.ArtistProfilePage')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.ExternalLinkType', verbose_name='Link type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
