# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artistprofilepage_artistsocialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofilelink',
            name='title',
            field=models.CharField(default='Nicole', max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistsocialmedialink',
            name='title',
            field=models.CharField(default='Nicole', max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
