# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 02:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20160605_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofilepage',
            name='bio',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
