# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0028_merge'),
        ('links', '0002_auto_20160605_1702'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('artists', '0005_auto_20160605_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSocialMediaContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('link_external', models.URLField(blank=True, verbose_name=b'External link')),
                ('handle', models.CharField(max_length=4000, verbose_name='Handle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ArtistSocialMediaLink',
        ),
        migrations.RenameField(
            model_name='artistprofilepage',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='artistprofilelink',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='artistprofilepage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='artistprofilepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofilepage',
            name='last_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='artistsocialmediacontact',
            name='artist',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmediacontact', to='artists.ArtistProfilePage'),
        ),
        migrations.AddField(
            model_name='artistsocialmediacontact',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='artistsocialmediacontact',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='artistsocialmediacontact',
            name='link_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.RelatedLinkType', verbose_name='Link type'),
        ),
    ]
