# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0028_merge'),
        ('artists', '0007_auto_20160605_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkAttributionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('link_external', models.URLField(blank=True, verbose_name=b'External link')),
                ('artist', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistartworklink', to='artists.ArtistProfilePage')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='artistartworkpagelink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='artistartworkpagelink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='artistartworkpagelink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='artworkattribution',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artworkattribution',
            name='artwork',
        ),
        migrations.DeleteModel(
            name='ArtistArtworkPageLink',
        ),
        migrations.DeleteModel(
            name='ArtworkAttribution',
        ),
    ]
