# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 14:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_auto_20160622_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsocialmediacontact',
            name='artist',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistsocialmediacontact', to='artists.ArtistProfilePage'),
        ),
    ]
