# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_auto_20160622_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistsocialmediacontact',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistsocialmediacontact',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='artistsocialmediacontact',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='artistsocialmediacontact',
            name='link_type',
        ),
        migrations.DeleteModel(
            name='ArtistSocialMediaContact',
        ),
    ]
