# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_auto_20160624_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofilepage',
            name='feed_image',
        ),
    ]
