# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=256, verbose_name='Symbol')),
                ('base_url', models.CharField(max_length=127)),
            ],
        ),
    ]
