# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalLinkType',
            new_name='RelatedLinkType',
        ),
    ]
