# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20160605_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedlinktype',
            name='base_url',
            field=models.URLField(max_length=127),
        ),
    ]
