# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20160622_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedlinktype',
            name='symbol',
        ),
        migrations.AddField(
            model_name='relatedlinktype',
            name='full_replace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relatedlinktype',
            name='prepend',
            field=models.BooleanField(default=False),
        ),
    ]
